### ISSUE TITLE
Missing atom feeds

### ISSUE THREAD

**Issue by amnezziaa** [ChtiJS/chtijs.francejs.org#118]
Atom feeds should be added at some point.
See for implementation: https://github.com/nfroidure/politics/blob/main/src/pages/blog/pages/%5Bpage%5D.tsx#L16-L19

**Comment by nfroidure** [comment]
Fixed with https://github.com/ChtiJS/chtijs.francejs.org/commit/d4c2e60ba0895afba26357aecf96b59c532cdac4
