### ISSUE TITLE
(Design) Page d'accueil sur 2 colonnes

### ISSUE THREAD

**Issue by 0gust1** [ChtiJS/chtijs.francejs.org#16]
Un truc que j'ai essayé de faire, mais sans vraiment y arriver.

Je voulais 2 conteneurs pour "Concept" et pour "Prochaine réunion", histoire de les mettre sur 2 colonnes.

Or, si on peut mettre du HTML dans le markdown, de façon assez logique tout le contenu markdown d'un bloc HTML est ignoré par le convertisseur markdown => html. Je croyais que c'était possible (j'ai un vague souvenir d'y être arrivé, ailleurs, dans d'autres situations... mais "vague" :) ). 

Bref, j'ai l'impression que si on veut ça (les 2 colonnes), il faut écrire toute cette zone en pur html, ou changer de syntaxe (certaines extensions à markdown font ce genre de choses... mais on s'éloigne du standard..)

**Comment by amnezziaa** [comment]
Outdated.
