### ISSUE TITLE
Conventions de code ?

### ISSUE THREAD

**Issue by kdisneur** [ChtiJS/chtijs.francejs.org#18]
Hello,

J'ai une question au sujet des conventions de code utilisées dans le projet. Suivez vous des conventions particulières ?

Cela pourrait ressembler à de l'hystérie mais c'est plutôt pour un point de vue de consistance du code. Par exemple : dans quel cas utilises tu des single quotes et dans quel cas utilises tu des double quotes ? Y a t'il des réglementations sur l'utilisation des ternaires ?

En Ruby (ou en coffeescript), par exemple, on utilise des double quotes quand on a besoin d'interpoler des variables et, le reste du temps, on utilise des single quotes. 

Pour Python, par exemple, on a pas le choix dans les conventions. Elles sont dictées par le PEP: http://www.python.org/dev/peps/pep-0008/

Pour Ruby il y a des conventions dictées par la communauté. À chaque projet de choisir le style qui l'intéresse : https://github.com/bbatsov/ruby-style-guide/ ou https://github.com/styleguide/ruby

Le JS ça ressemble plus à Ruby il y'a une multitude d'écoles. Celles dictées par Google, par Airbnb, ...
Avez vous décidé d'en suivre et si oui lesquelles ?

**Comment by nfroidure** [comment]
@Gillespie59 chaud pour nous faire une tite config eslint ? ;)

**Comment by Gillespie59** [comment]
Pas de soucis ;) je vais essayer de faire cela demain.

**Comment by flexbox** [comment]
Et je sais pas si on peux le binder avec http://editorconfig.org ? 

// David Leuliette 
// Front-end developer
→ http://davidl.fr

**Comment by Gillespie59** [comment]
Avec un peu de retard : https://gist.github.com/Gillespie59/29c5775c76fece9d05ab

Désolé

**Comment by neemzy** [comment]
Go PR?

**Comment by Gillespie59** [comment]
@neemzy tu parles à moi ?  si je ne m'abuse, vous n'utilisez pas ESLint sur le site du ChtiJS.

**Comment by nfroidure** [comment]
Yep, y'a rien pour le moment, je peux intégrer ESLint avec nos règles si vous voulez : https://github.com/SimpliField/sf-lint

Je dois juste adapter le module pour utiliser les shared configs avant ça sera plus clean.

**Comment by neemzy** [comment]
@Gillespie59 Justement, go PR! :)
@nfroidure Ça me va, faudrait juste bien s'assurer de les rendre autonomes pour qu'on puisse PR dessus s'il y a des trucs qu'on n'aime pas :)

**Comment by nfroidure** [comment]
@neemzy yep, on a un système d'issues en interne pour changer certains paramètres, on peut l'utiliser et voir, si nos conventions sont trop contraignantes/différentes on forkera un truc spécialement pour ChtiJS.

**Comment by nfroidure** [comment]
Voilà:  
https://github.com/ChtiJS/chtijs.francejs.org/blob/master/.eslintrc

Au pire, on peut overrider des règles direct dans le .eslintrc, mais du coup, je propose qu'on utilise le même format d'issue : [rule-name] Titre
