### ISSUE TITLE
Planète blogs

### ISSUE THREAD

**Issue by nfroidure** [ChtiJS/chtijs.francejs.org#29]
On en a parlé à l'occasion du dernier ChtiJS. Le planète est en place pour la version Gulp du build.

N'hésitez pas à ajouter le votre et à reporter/fixer tout souci. L'ajout se fait ici : 
https://github.com/ChtiJS/chtijs.francejs.org/blob/gulp/config.dat#L25

**Comment by amnezziaa** [comment]
Resolved.
