### ISSUE TITLE
Choix du système de template

### ISSUE THREAD

**Issue by nfroidure** [ChtiJS/chtijs.francejs.org#3]
Si on part sur du statique, il nous faudra un système de template. L'idéal serait une système de template qui puisse être utilisé indépendamment en back et en front, streamable et non destructif si possible. Des idées ?

**Comment by nfroidure** [comment]
Bon, ça a bien vielli tout ça :D. J'allais fermer l'issue, mais je me suis dit pourquoi pas refaire les templates avec React ? @neemzy ?

**Comment by neemzy** [comment]
Je suis potentiellement chaud pour bosser dessus étant donné que je voulais expérimenter le server-side rendering avec React. On peut aussi demander conseil aux copains de P!, je crois qu'ils ont fait un truc similaire récemment.

Je serai hélas probablement pas là au prochain meetup, mais si c'est pas urgentissime je suis tout à fait disposé à en discuter la prochaine fois (je suis preneur de conseils aussi).

Ou sinon on se boit un verre à Euratech dans un futur proche avec @victordarras :)

**Comment by flexbox** [comment]
@neemzy Oubliez pas de me pinger alors je suis dans les couloir d'euratech en ce moment :D

**Comment by flexbox** [comment]
@neemzy Oubliez pas de me pinger alors je suis dans les couloirs d'euratech en ce moment :D

**Comment by nfroidure** [comment]
Ben, faut se faire un déjeuner ChtiJS :+1:

**Comment by nfroidure** [comment]
Ben, faut se faire un déjeuner ChtiJS :+1:  :p

**Comment by neemzy** [comment]
Bon pour info, c'est le prochain item dans ma todo, donc en théorie je reviens bientôt vers vous avec un premier jet de la version React :)

**Comment by neemzy** [comment]
Bon en fait j'ai pas le temps, mais je filerai un coup de main avec plaisir si quelqu'un prend le point. Déso :/
