### ISSUE TITLE
Vidéos des confs

### ISSUE THREAD

**Issue by nfroidure** [ChtiJS/chtijs.francejs.org#37]
J'ouvre un sujet pour lancer le débat de manière traçable.

@thomassloboda as-tu pu visionner ton enregistrement ? La qualité te semble bonne ?
 Peux-tu aussi les transmettre à @oncletom ?

On part sur YouTube DailyMotion ou les deux pour la publication ?

++

**Comment by nfroidure** [comment]
Fixé par Lille Web

Il faudrait voir si pas possible d'embeder les diverses vidéos dans les compte rendu de meetups

**Comment by flexbox** [comment]
:+1:
