### ISSUE TITLE
Example de .token

### ISSUE THREAD

**Issue by victordarras** [ChtiJS/chtijs.francejs.org#38]
Hello all,
j'ai une sacré lacune par rapport à l'utilisation du gruntfile, est-ce que l'un de vous pourrez me donner un exemple de fichier .token qui permet d'utilise l'API de github , limite en mettre un par défaut qui ne marche pas dans le repo, histoire d'avoir juste à le modifier avec des infos que je générer moi même.

**Comment by nfroidure** [comment]
Résolu
