### ISSUE TITLE
Erreur lors du lancement de gulp

### ISSUE THREAD

**Issue by victordarras** [ChtiJS/chtijs.francejs.org#48]
Hello tout le monde, j'ai une erreur après avoir installé les paquets npm en lancant gulp, voilà un screen :
http://grab.by/Kwsi
J'ai du me tromper quelque part dans l'install, si vous avez une idée je suis preneur.

**Comment by nfroidure** [comment]
Apparemment tu as pas setté le token GitHub, essaie avec l'option `--noreq`.

**Comment by nfroidure** [comment]
L'option est documentée ici https://github.com/ChtiJS/chtijs.francejs.org#pour-travailler-dessus- mais on devrait mettre entre backquotes pour la rendre plus visible. Si tu as 2 sec ;).

**Comment by victordarras** [comment]
J'ai la même erreur avec l'option --noreq x)

**Comment by neemzy** [comment]
Sinon utilise un token :) C'est juste la mort sans

**Comment by victordarras** [comment]
Idem avec un token.
Qui est bien à rajouter à la racine du projet sous le nom .token si je ne m'abuse ?

**Comment by nfroidure** [comment]
Je regarderai ce soir, en attendant, tu peux coller le résultat de:
```sh
node -v
npm -v
```

**Comment by victordarras** [comment]
Yep merci Nico
```
$ node -v
v0.12.7
$ npm -v
2.12.1
```

**Comment by nfroidure** [comment]
ps: tu as refais un npm install ?

**Comment by victordarras** [comment]
Oui oui, après avoir supprimé le dossier node_modules.
